CREATE TABLE if NOT EXISTS posts (
    id BIGSERIAL PRIMARY KEY,
    content VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    user_id BIGSERIAL NOT NULL,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW()
)